version: '3'

services:
  database:
    container_name: database_flask
    hostname: database
    image: postgres:12
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - /tmp:/tmp

  backend:
    container_name: backend_flask
    hostname: backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database