version: '3'

services:
  backend:
    container_name: backend_flask
    hostname: backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database