[default]
DEBUG = false
FLASK_ADMIN_NAME = "Rooms Scheduler App | Admin"
FLASK_ADMIN_TEMPLATE_MODE = "bootstrap3"
FLASK_ADMIN_SWATCH = 'cerulean'
TITLE = "Rooms Scheduler App"
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
SECRET_KEY = 'YourSecretKey'
SQLALCHEMY_DATABASE_URI = 'postgresql://user:pass@localhost:5432/db_name'
EXTENSIONS = [
    "rooms_scheduler_app.ext.appearance:init_app",
    "rooms_scheduler_app.ext.database:init_app",
    "rooms_scheduler_app.ext.auth:init_app",
    "rooms_scheduler_app.ext.admin:init_app",
    "rooms_scheduler_app.ext.commands:init_app",
    "rooms_scheduler_app.blueprints.webui:init_app",
    "rooms_scheduler_app.blueprints.restapi:init_app",
]


[development]
EXTENSIONS = [
    "flask_debugtoolbar:DebugToolbarExtension",
    "dynaconf_merge_unique"  # to reuse extensions list from [default]
]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true
DEBUG_TOOLBAR_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PANELS = [
    "flask_debugtoolbar.panels.versions.VersionDebugPanel",
    "flask_debugtoolbar.panels.sqlalchemy.SQLAlchemyDebugPanel",
    "flask_debugtoolbar.panels.timer.TimerDebugPanel",
    "flask_debugtoolbar.panels.headers.HeaderDebugPanel",
    "flask_debugtoolbar.panels.request_vars.RequestVarsDebugPanel",
    "flask_debugtoolbar.panels.template.TemplateDebugPanel",
    "flask_debugtoolbar.panels.route_list.RouteListDebugPanel",
    "flask_debugtoolbar.panels.logger.LoggingPanel",
    "flask_debugtoolbar.panels.profiler.ProfilerDebugPanel",
    "flask_debugtoolbar.panels.config_vars.ConfigVarsDebugPanel"
]
